/* Configuration for great_circle_distance generated by Alire */
#ifndef GREAT_CIRCLE_DISTANCE_CONFIG_H
#define GREAT_CIRCLE_DISTANCE_CONFIG_H

#define CRATE_VERSION "0.1.0-dev"
#define CRATE_NAME "great_circle_distance"

#define ALIRE_HOST_OS "macos"

#define ALIRE_HOST_ARCH "aarch64"

#define ALIRE_HOST_DISTRO "homebrew"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
